const AppStrings = {
  APP_NAME: "MyCarSafety",
  ENGLISH_CODE: "en",
  ARABIC_CODE: "ar",
  LOCAL: "local",
  PLEASE_LOGIN: "برجاء تسجيل الدخول",
  PLEASE_TYPE_YOUR_EMAIL: "برجاء ادخال البريد الالكتروني",
  EMAIL: "البريد الالكتروني",
  EMAIL_HINT: "safetyCar@gmail.com",
  NAME: "الاسم",
  TYPE_YOUR_NAME: "اكتب اسمك",
  PLEASE_TYPE_YOUR_NAME: "من فضلك ادخل اسمك",
  ENGINE_TYPE: "نوع المحرك",
  CREATE_YOUR_ACCOUNT: "قم بأنشاء حسابك",
  RESET_PASSWORD: "استعادة كلمة المرور",
  seats: "مقاعد",
  PASSWORD: "كلمة المرور",
  ADULT: "راكب بالغ",
  CHILDREEN: "أطفال",
  SAFETY_Assistants: "مساعدات السلامة",
  STREET_WALKER: "عابر الطريق",
  REGISTER: "تسجيل",
  SAFETY_RATES: "تقيمات السلامة",
  PASSWORD_HINT: "كلمة المرور الخاصة بك",
  FORGOT_PASSWORD: "نسيت كلمة المرور؟",
  CREATE_ACCOUNT: "انشاء حساب",
  ALREADY_HAVE_ACCOUNT: " لديك حساب بالفعل؟",
  WHAT_YOU_SEARCHING_FOR: "عن ماذا تبحث؟",
  BRANDS: "البراندات",
  MOST_SEARCHED_CARS: "السيارات الأكثر بحثا",
  MAYBE_YOU_LIKE: "ربما تحب ايضا",
  OVERVIEW: "نظره عامة",
  LOGIN_AS_GUEST: "دخول كا زائر",
  OR: "أو",
  SHOW_DETAILS: "عرض التفاصيل",
  SHOW_MORE_DETAILS: "عرض تفاصيل اكثر",
  LOGIN: "تسجيل الدخول",
  INVALID_EMAIL_ADDRESS: "بريد الكتروني غير صحيح",
  PASSWORD_IS_REQUIRED: "من فضلك ادخل كلمة المرور",
  EMAIL_IS_REQUIRED: "بريد الكتروني مطلوب",
  PLEASE_MAKE_PASSWORD_MORE: "كلمة المرور قصيرة جدا",
  CHECK_YOUR_MAIL_PLEASE: "تحقق من بريدك الالكتروني لاستعادة كلمة المرور",
  NO_INTERNET_ERROR: "لا يوجد اتصال بالانترنت",
  SOMETHING_WENT_WRONG: "حدث خطأ ما",
  USER_NOT_FOUND: "البريد الالكتروني غير مسجل",
  INVALID_PASSWORD: "تحقق من صحه البيانات",
  EMAIL_ALREADY_EXISTS: "البريد الالكتروني مسجل بالفعل",
  INVALID_EMAIL: "تحقق من صحه البيانات",
  LOGIN_GUEST: "دخول كا زائر",
};
export default AppStrings;
